apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: africa-south1-docker.pkg.dev/k8s-project-468723/my-docker-repo/my-python-app:v1
        ports:
        - containerPort: 5000
